alias brewup='brew update; brew upgrade; brew prune; brew cleanup; brew doctor'
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

source ~/.rvm/scripts/rvm
